id: P000653
initial_creation_type: ocr
source_metadata:
  id: bdr:W22353
  title: སངས་རྒྱས་ཀྱི་མཚན་ལྔ་སྟོང་བཞི་བརྒྱ་ལྔ་བཅུ་རྩ་གསུམ་པ། ༼སྐུ་འབུམ་པར་མ།༽
  author: ''
  volumes:
    bd90097174bc46cb8e38490de61812d5:
      image_group_id: I1KG9678
      title: ''
      volume_number: 1
      total_pages: 848
